### PR TITLE
C++20 fixes

### LINKED ISSUE #10022: LLVM doesn't compile on VS 16.9.2
On VS 16.9.2 LLVM won't compile. This potentially will be an issue once azure is on that version.
The errors:
`1>C:\Users\redacted\Desktop\rpcs3\llvm\include\llvm/Support/DebugCounter.h(80,1): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`
`1>C:\Users\redacteds\Desktop\rpcs3\llvm\include\llvm/Support/SuffixTree.h(278,1): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`
`1>C:\Users\redacted\Desktop\rpcs3\llvm\lib\Support\SuffixTree.cpp(85,46): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`
`1>C:\Users\redacted\Desktop\rpcs3\llvm\lib\Support\VirtualFileSystem.cpp(1257,1): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`

### PR DESCRIPTION
**Pull request by xddxd**
C++20 fixes taken from LLVM upstream. Fixes compilation on VS 16.9.2 and clang-cl.
Fixes https://github.com/RPCS3/rpcs3/issues/10022.

### CODE REVIEW

**Comment by xddxd** [comment]
Linux will probably fail a few times because I don't have Linux installed so I couldn't test.

EDIT: It passes now.

**Comment by xddxd** [comment]
Looks like it's good to go.
